# Generated by Django 3.0.5 on 2020-05-03 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitap', '0003_auto_20200503_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('kitap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitap.Kitap')),
            ],
        ),
    ]
