# Generated by Django 3.0.5 on 2020-05-04 02:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitap', '0005_auto_20200503_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitap',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
