# Generated by Django 3.0.5 on 2020-05-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitap', '0009_auto_20200506_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitap',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
