# Generated by Django 3.0.5 on 2020-05-08 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200508_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopcart',
            old_name='kitap',
            new_name='product',
        ),
    ]
