# Generated by Django 3.0.5 on 2020-05-08 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_orderproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='stok_drum',
            new_name='stok_durum',
        ),
    ]
